Disabled Derivation Application calls

diff --git a/readAVM/work/mailscript b/readAVM/work/mailscript
--- a/readAVM/work/mailscript
+++ b/readAVM/work/mailscript
@@ -15,7 +15,7 @@
 \rm -rf msg0
 
 #run derivation on the total plant power release
-derivation $APP_USER $HDB_LOCAL 5035
+#derivation $APP_USER $HDB_LOCAL 5035
 
 # now create Glen Power Release, assume new data for yesterday
 # NASTY HACK!
@@ -28,11 +28,11 @@ yesterday=`/usr/local/bin/date +%y%b%d -d 'yesterday' | tr '[a-z]' '[A-Z]'`
 #    echo "Glen Power Release failed."
 #fi
 
-../../scadaTransfer/src/derive_pwr
-if [ $? -ne 0 ]
-    then
-    echo "derivation for Power Release failed!"
-fi
+#../../scadaTransfer/src/derive_pwr
+#if [ $? -ne 0 ]
+#    then
+#    echo "derivation for Power Release failed!"
+#fi
 
 # we need to calculate a new glenTotRelease,
 # but we may not have data in the database! Try it anyway, and no big deal
@@ -44,11 +44,11 @@ fi
 #    echo "Glen Total Release failed!"
 #fi
 
-../../scadaTransfer/src/derive_tot
-if [ $? -ne 0 ]
-    then
-    echo "derivation for Total Release failed!"
-fi
+#../../scadaTransfer/src/derive_tot
+#if [ $? -ne 0 ]
+#    then
+#    echo "derivation for Total Release failed!"
+#fi
 #massive HACK here, how do we know which date to send data to hydromet for?
 scadaData app_user uchdb2 $yesterday
 if [ $? -ne 0 ]
